source "http://rubygems.org"
# Add dependencies required to use your gem here.
gem 'twitter'
gem 'awesome_print'
gem 'tweetstream'
gem 'resque'
gem 'redis', '3.0.0'
gem 'activerecord'
gem 'pg'
gem 'capistrano'
gem 'capify-ec2'
gem 'god'
gem 'activesupport'


# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do

  gem "rdoc", "~> 3.12"
  gem "bundler"
  gem "jeweler", "~> 1.8.3"
  gem "rcov", ">= 0"
  gem 'rspec'
  gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'growl'
  gem "rspec-core"
  gem "rspec-expectations"
  gem "rspec-mocks"
end
